theme: jekyll-theme-minimal
logo: https://fffuture.work/dogbot-lp/images/logo.png
title: Dog reminder (クローズドβテスト中)
description: 日々の面倒なルーチンワークをらくらく自動化 Dog bot
show_downloads: false
google_analytics: UA-178643334-1
